# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-03 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usepoll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('experience', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
            ],
        ),
    ]
