# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usepoll', '0003_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='image_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
