# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usepoll', '0004_coach_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='bio',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='exercise',
            name='coach',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='usepoll.Coach'),
        ),
    ]
