# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usepoll', '0006_auto_20160208_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='city',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='gym',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='gym',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
