# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usepoll', '0007_auto_20160208_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
